### ISSUE TITLE
An h5 dataset path typo in read_detector_data

### ISSUE THREAD

**Issue by ivan-usov** [paulscherrerinstitute/pyzebra#1]
https://github.com/paulscherrerinstitute/pyzebra/blob/0e495b60cd035e86d09df90c30532b69fe044805/pyzebra/h5.py#L53

@zaharko probably, the path should read "/entry1/sample/phi" instead.

Also note the absence of 'ZEBRA' in path. This should also be the case for all these variables:
https://github.com/paulscherrerinstitute/pyzebra/blob/0e495b60cd035e86d09df90c30532b69fe044805/pyzebra/h5.py#L52-L54

**Comment by zaharko** [comment]
Sure, this was a typo
