### ISSUE TITLE
hkl order in comm_export

### ISSUE THREAD

**Issue by ivan-usov** [paulscherrerinstitute/pyzebra#14]
The order of hkl indices in exported files is somewhat unusual:
https://github.com/paulscherrerinstitute/pyzebra/blob/32d75988b77ce4f8330f78f2fc94cc92fb84b759/pyzebra/comm_export.py#L69-L71

@JakHolzer , @zaharko Is it correct that comm/incomm files require that order? Feel free to close it, if that's the case.

**Comment by JakHolzer** [comment]
Hello Ivan,
thank you for pointing that out. It wrong, the order needs to be hkl, not
hlk. I shall fix it immediately.
Thans!
Jakub

čt 22. 10. 2020 v 15:13 odesílatel Ivan Usov <notifications@github.com>
napsal:

**Comment by ivan-usov** [comment]
@rsibille-psi FYI, in case you already exported some files

**Comment by ivan-usov** [comment]
Fixed in 0347566aeb16fc7c84d10d01dc9b289c69c110b1

@JakHolzer , also could you write "Fix #.." in the commit title/message, so that when pushed to master it will automatically close the corresponding issue? Thanks!
