### ISSUE TITLE
Peakfit fails without peakfind step even when peakfind doesn't locate any peaks

### ISSUE THREAD

**Issue by ivan-usov** [paulscherrerinstitute/pyzebra#16]
Open any data file, press "Fit Current" or "Fit All". This fails with the following error:
```
  File "/das/home/usov_i/pyzebra/pyzebra/fit2.py", line 62, in fitccl
    if len(scan["peak_indexes"]) > 1:
KeyError: 'peak_indexes'
```
What should be happening is that the fitting procedure tries to fit data as if there were no peak detected.

**Comment by JakHolzer** [comment]
I dont see why someone would do this, but we can add to the no peak
scenario directly, I'll do it in few minutes

pá 30. 10. 2020 v 15:09 odesílatel Ivan Usov <notifications@github.com>
napsal:
