### ISSUE TITLE
Lorentz correction not applied to area sigma

### ISSUE THREAD

**Issue by ivan-usov** [paulscherrerinstitute/pyzebra#18]
After some refactoring I noticed that the lorentz correction is applied only to area, but not to it's sigma:
https://github.com/paulscherrerinstitute/pyzebra/blob/4343d6e2b6c51c9c2041781de7d7fb7d0604c7b3/pyzebra/ccl_io.py#L252-L262

I wonder, if it should also influence the resulting area sigma, @JakHolzer ? Feel free to close the issue, if the lorentz correction should affect only the area value.

**Comment by JakHolzer** [comment]
Thats a very good point, however I'm not sure. I suggest to raise the
question on thursday and deal with it after Oksana decides.

út 10. 11. 2020 v 16:28 odesílatel Ivan Usov <notifications@github.com>
napsal:

**Comment by ivan-usov** [comment]
@zaharko , @rsibille-psi do you have any comments on that?

**Comment by rsibille-psi** [comment]
Yes, I would say that the Lorentz correction should also affect the area sigma.
This is multiplying a measurement value with an exact number, thus we should multiply the uncertainty also with that exact number.

**Comment by ivan-usov** [comment]
Fixed in 008761e661a62b302a13d54afe267f81e70e98d6
