### ISSUE TITLE
hkl indices converted to int also for .incomm files

### ISSUE THREAD

**Issue by ivan-usov** [paulscherrerinstitute/pyzebra#19]
In a situation, where `hkl` indices are real numbers the export file extension is `.incomm`. However, in the export function they are converted to integers:
https://github.com/paulscherrerinstitute/pyzebra/blob/b5b77d165abb866c9d60656bc428eb61062b1fe2/pyzebra/ccl_io.py#L241-L243

This doesn't look correct.

**Comment by zaharko** [comment]
I think this is working correct now, but I ask for a possibility to extend format up to 4 digits after comma.
A default format - 2 digits, but exceptionally user should be able to request till 4 digits.

**Comment by zaharko** [comment]
ccl_intergation:
In the table on the left all hkl indices are integers, which is not correct.

**Comment by ivan-usov** [comment]
I think the best would be to auto-detect if there is a need for more digits after comma (with a minimum of 2 and a maximum of 4). The output will be formatted accordingly.

**Comment by ivan-usov** [comment]
Would it be also ok to export numbers with trailing 0s truncated? In other words:
1.23456 -> 1.2345 (max 4 digits)
1.2340 -> 1.234
1.000 -> 1 (here, i'm not sure if you'd like to have 1.00)

**Comment by ivan-usov** [comment]
The issue with hkl indices in the table is fixed in 0d8a30b995c407a87b0beee952e66b3ea184f384

**Comment by zaharko** [comment]
Okay to:
> 1.23456 -> 1.2345 (max 4 digits)
> 1.2340 -> 1.234

This should be truncated to the same amount of digits as other indices, i.e. if request is 4 digits, then for all h, k and l

> 1.000 -> 1 (here, i'm not sure if you'd like to have 1.00)
>
