### ISSUE TITLE
Issue with variables for 2d viewer

### ISSUE THREAD

**Issue by rsibille-psi** [paulscherrerinstitute/pyzebra#20]
Presently the 2d viewer cannot read data if the variable is not omega (om). We would need to have it working with any angle (stt, phi, chi).

Present error:

KeyError: "Unable to open object (object 'rotation_angle' doesn't exist)"

**Comment by ivan-usov** [comment]
@rsibille-psi , do you expect multiple angles to vary within the same 2d dataset? If yes, then we could make an angle manually selectable, if not, we should be able to determine one automatically, so no extra user input would be needed.

**Comment by rsibille-psi** [comment]
Only one angle should change and therefore the aim is indeed to determine which one automatically.
