### ISSUE TITLE
October 21 

### ISSUE THREAD

**Issue by zaharko** [paulscherrerinstitute/pyzebra#41]
**1. ccl integrate**
- [x] 1.1. It will be useful to extend horizontally the table with scans and to write there the scan center angles (either bi- or nb- geometries):
For bi: 2theta,omega, chi and phi
For nb: 2theta,omega, nu
There is no place to display the whole table, it can be good to introduce a horizontal scrolling with the option to scroll to the 'hidden' columns with the scan center angles
- [x] 1.2 Presently, there is a bug in the following procedure: if scans are integrated automatically and then one scan is integrated manually the 'export' key is reset for all scans. Skip this reset. How to reproduce the bug:
  1. Open new for 3803.ccl
  2. Click Process All
  3. In scan 1 (for example) change export flag to false. Scan 1 fit result is removed from export window as they should be.
  4. click on scan 2
  5. click Process Current - export flag on scan 1 changes back to true and the scan 1 fit result is back in export window.

**2. param study** 
- [x] 2.1 When multiple files are selected check N of points and scan motor.
When N of points is zero give a warning comment in the server output and exclude this file from processing.
When following files have the scan motor different from the fist file give a warning comment in the server output and do not process the files further

**3. hdf viewer**
- [x] 3.1 Add an "Open" button which would allow to read the content of the file when it is update
- [x] 3.2 add the second axis on top of the 'Projections on X-axis' and 'Projections on Y-axis'. These are Gamma and nu, respectively.
The `gamma` in /entry1/ZEBRA/area_detector2/polar_angle is the `gamma_central` (and similarly `nu` in /entry1/ZEBRA/area_detector2/tilt_angle).
Our resolution depends on the size of the pixel and the distance from the sample to the detector.
The sizes of the pixel are stored in /entry1/ZEBRA/area_detector2/x_pixel_size and ../y_pixel_size, these are
xscale=0.734 mm in the horizontal direction (gamma) and yscale=1.4809 in the vertical direction (nu)
The distance form the sample to the detector is stored in /entry1/ZEBRA/area_detector2/distance.
In majority of cases it is 538 mm.
The deviation of the gamma_current from the gamma_central in angular units (deg):
Atan (N_pixels_from_the_center *pixel size/distance)
- [x] 3.3 Introduce new features in the table of spind events. 
- [x] 3.3.1 'Add/remove spind event' should be renamed into 'add/remove peak center'
- [x] 3.3.2 Switch between 2 tables via tabs. The available table will have the title line 'Actual peak center'. The new one 'Peak in the detector center'.
How to calculate the angles to bring the peak in the detector center?
For the nb-geometry: chi and phi should be skipped (no number in the cell) and x,y,gamma,nu should be recalculated into to gamma, omega, nu at x=128, y=64 using det2pol from xtal.py
For the bi-geometry: x,y,gamma,omega, chi,phi,nu should be recalculated to gamma, omega, chi, phi at x=128, y=64, nu=0 using sequence of routines as in angtohkl from xtal.py

**4. ccl compare**
- [ ] We need a tab derivative of 'ccl integrate' which allows to compare two datasets with visualisation.
Ivan agreed to prepare a tab draft and Camilla to work on its functionality.

**Comment by ivan-usov** [comment]
@rsibille-psi , in a view of https://github.com/paulscherrerinstitute/pyzebra/issues/43, would splitting the table into two for nb- and bi- geometries also be fine for ccl compare? I guess, both files will have the same geometry, so all scans will occupy one of the tables only. Another question, will both ccl files be in the same folder? If yes, then I can simplify opening procedure to selecting 2 files from a list of all ccl files in a particular proposal_id folder.

**Comment by rsibille-psi** [comment]
> @rsibille-psi , in a view of #43, would splitting the table into two for nb- and bi- geometries also be fine for ccl compare?
yes

 I guess, both files will have the same geometry, so all scans will occupy one of the tables only. 
yes

Another question, will both ccl files be in the same folder?
yes

 If yes, then I can simplify opening procedure to selecting 2 files from a list of all ccl files in a particular proposal_id folder.
yes

**Comment by ivan-usov** [comment]
@rsibille-psi thank you for your feedback, though I discovered that splitting the table might be more difficult than expected. Maybe I'll return to it later if you still think it significantly improves UX.

Could you also provide an example of data for ccl compare?
