### ISSUE TITLE
ccl integrate tables with angles

### ISSUE THREAD

**Issue by zaharko** [paulscherrerinstitute/pyzebra#43]
'Ccl integrate'
 nb-geometry
Gamma is missing.
The systematic way would be to have different subtables for bi- and nb- geometries
For bi- 2theta, om, chi,phi
For nb - gamma, om, nu
<img width="1630" alt="ccl_integrate_nb_20211532" src="https://user-images.githubusercontent.com/50512596/140739704-b4ddb41a-1a1e-4004-9147-f94d17cb54d3.png">

**Comment by ivan-usov** [comment]
Based on 1.1 in https://github.com/paulscherrerinstitute/pyzebra/issues/41 it was `2theta` for both, bi- and nb-geometries. 
But I can add a new column `gamma` to fix the current issue.

Ok, splitting all scans into 2 tables based on their geometries sounds like an option. The only tradeoff I see is that if all scans are of the same geometry, the second table will just occupy space. Though, maybe it's also helpful to know there are only one geometry scans. Which option would you prefer?

**Comment by ivan-usov** [comment]
Splitting the table might be more difficult than expected. Maybe I'll return to it later if you still think it significantly improves UX.
