### ISSUE TITLE
ccl prepare

### ISSUE THREAD

**Issue by zaharko** [paulscherrerinstitute/pyzebra#50]
Graphics (plot selected file) is not implemented

**Comment by ivan-usov** [comment]
There is already a possibility of .ccl files plotting in ccl_prepare tab (based on Camilla's notebook), added in: https://github.com/paulscherrerinstitute/pyzebra/commit/a192648cc4774a07038afe92fe6e36f8b2999fd2

Though, plotting of other data formats can be added if needed.

**Comment by ivan-usov** [comment]
hkl/mhkl plotting was added in bb8c158591f8c1abfe74474f74567763f7477576
