### ISSUE TITLE
plot maps in three panels

### ISSUE THREAD

**Issue by zaharko** [paulscherrerinstitute/pyzebra#51]
- [ ] 1. plot data  panel
  - [x] a. Increase the area for plotting maps for both hdf and ccl (increase horizontal and vertical axes by about 25%)
  - [x] b. ccl data: 
    - [x] b1. skip labeling, axes for the orthogonal coordinate system
    - [x] b2. introduce hkl labels when mouse is clicked at(near) the hkl position from measured ccl or calculated hkl/mhkl files
    - [x] b3. switch off/on legend with displayed ccl files, k-vectors
  - [ ] c. hdf data:
    - [ ] c1. adopt the change of the 'in-plane X' and 'normal' directions to the user defined ones
    For this three value should be changed in teh cell 3 of Camilla's code
    ##x_dir should be changed to 'in-plane X'
    x_dir = [1,1,0]
    ##orth_dir should be changed to 'normal' 
    orth_dir = [-1,1,0] 
    ##and orth_cut should be changed to 'cut'
    orth_cut = 0.0
    - [x] c2. add colorbar
    - [x] c3. add log scale intensity option
    - [ ] c4. correct plot of the hkl/mhkl positions 
- [x] 2. ccl prepare panel
  - [x] a. Increase the area for plotting maps for ccl (increase horizontal and vertical axes by about 25%)
  - [x] b. skip labeling, axes for the orthogonal coordinate system
  - [x] c. introduce hkl labels when mouse is clicked at(near) the hkl position from calculated hkl/mhkl files
- [x] 3. hdf viewer panel
  - [x] a. Increase the area for plotting maps for hdf (increase horizontal and vertical axes by about 20%)
  - [x] b. add log scale intensity option (the option would apply log scale generally on the panel, i.e. to both projections and frame plots)

**Comment by ivan-usov** [comment]
There is a problem with the logarithmic color mapping, namely, it can't include 0 values in data as it refers to -infinity on the axis. Unfortunately, the 2D detector data almost always includes 0 values (as background). Thus, we can't include it as it is.

There are a few workaround possibilities, but none of them are perfect. In fact, many argue that count data should not be log-transformed: 
https://www.nature.com/articles/npre.2010.4136.1

I'll hold this change for now.

**Comment by zaharko** [comment]
Hi Ivan,

Could we change zeroes into the small number C for which log can be taken and plot the data shifted by C?
This might be strictly speaking not the correct solution, but it will serve the purpose to see a weak signal on top of  a significant background.

Thank you
Oksana

On 15 Feb 2023, at 16:07, Ivan Usov ***@***.******@***.***>> wrote:



There is a problem with the logarithmic color mapping, namely, it can't include 0 values in data as it refers to -infinity on the axis. Unfortunately, the 2D detector data almost always includes 0 values (as background). Thus, we can't include it as it is.

There are a few workaround possibilities, but none of them are perfect. In fact, many argue that count data should not be log-transformed:
https://www.nature.com/articles/npre.2010.4136.1

I'll hold this change for now.
