### ISSUE TITLE
format of FULLPROF output files

### ISSUE THREAD

**Issue by rsibille-psi** [paulscherrerinstitute/pyzebra#52]
In .comm files exported from the 'ccl integrate' and 'ccl compare' tabs, the first column (a label for the number of the reflection in the file) should start from 1 instead of 0 at the moment.

**Comment by ivan-usov** [comment]
Hi @rsibille-psi , I can see that the first column in .comm files is a scan number taken from ccl/dat files and it starts from 1, i.e.:
```
.comm file:
     1   2  -2   1  11820.35    359.14   32.61   16.31  117.95  168.97
     2   2   0   1   9211.22    260.99   32.61   16.31  141.03   98.15
     3   0  -2   1  10319.26    410.16   32.61   16.31  158.89 -155.78
     4   3  -2   0   5727.40    133.91   34.83   17.42  102.89    6.85
     5   3  -1   0   5226.74     95.06   34.83   17.42  121.19   41.85
``` 
Where is that label for the number of the reflection in the file?

**Comment by rsibille-psi** [comment]
Hi Ivan,

Yes it seems that this has changed last year with Nicos, so that now the scan number in ccl files starts from 0 (python...) while it started with 1 for files generated by SICS.
Our suggestion is that, if a scan number is zero, pyzebra should just change that 0 and write a 1, without renumbering the entire series.
Thanks.

Best wishes,

Romain

**Comment by ivan-usov** [comment]
The test server should contain a fix now, so if the scan number in a ccl file starts from 0, it's index during processing will be changed to 1 (it basically means that there will always be two scans with an index 1 in such cases).

I though to wait for #51 to be fixed fully before updating the main server, but let me know if it will take longer, so we can do it maybe already now.
