### ISSUE TITLE
hdf param module

### ISSUE THREAD

**Issue by zaharko** [paulscherrerinstitute/pyzebra#56]
In the main and temporary servers the hdf files can be read and processed one-by-one, but 'process all' results in unreasonable values. I used the proposal 20230062 files 211-223

**Comment by ivan-usov** [comment]
It seems that it's an issue of a range variation, where a peak could move. One could try to move the zoom area around and refit with "Process All". Often, the results will change. So, for the best results in this type of situations, fitting needs to be done individually for each file with a corresponding zoom area.
